---
- name: Install & Setup Infisical CLI
  hosts: debian
  become: true
  vars_files:
    - ../vault.enc
  tasks:
    - name: Check if Infisical CLI is installed
      ansible.builtin.command: infisical --version
      register: infisical_check
      changed_when: false
      failed_when: false

    - name: Add Infisical apt repository
      ansible.builtin.shell: curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: infisical_check.rc != 0

    - name: Install Infisical CLI
      ansible.builtin.apt:
        name: infisical
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: infisical_check.rc != 0
