- name: Prune Docker Images
  hosts: debian
  become: true
  tasks:
    - name: Prune unused Docker images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
